# Generated by Django 6.0.3 on 2026-06-18 13:41

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_accounthead_journalentry_cashtransaction_journalline"),
    ]

    operations = [
        migrations.CreateModel(
            name="LabUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("username", models.CharField(max_length=150, unique=True)),
                ("password", models.CharField(max_length=128)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("supervisor", "Supervisor"),
                            ("staff", "Staff"),
                        ],
                        default="staff",
                        max_length=20,
                    ),
                ),
                ("permissions", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "lab_users",
                "ordering": ["role", "username"],
            },
        ),
        migrations.AddField(
            model_name="loginsession",
            name="last_activity",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="loginsession",
            name="token",
            field=models.CharField(
                default=accounts.models.generate_token, max_length=64, unique=True
            ),
        ),
    ]
