# Generated by Django 6.0.3 on 2026-05-18 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("department_code", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=120, unique=True)),
                ("report_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "departments",
                "ordering": ["report_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doctor_code",
                    models.CharField(blank=True, max_length=30, null=True, unique=True),
                ),
                ("name", models.CharField(max_length=150)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("address", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "doctors",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Hospital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hospital_code",
                    models.CharField(blank=True, max_length=30, null=True, unique=True),
                ),
                ("name", models.CharField(max_length=150)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("address", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "hospitals",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient_code",
                    models.CharField(blank=True, max_length=30, null=True, unique=True),
                ),
                ("full_name", models.CharField(max_length=150)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("age_years", models.PositiveIntegerField(default=0)),
                ("age_months", models.PositiveIntegerField(default=0)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("address", models.TextField(blank=True)),
            ],
            options={
                "db_table": "patients",
                "ordering": ["full_name", "id"],
                "indexes": [
                    models.Index(
                        fields=["full_name"], name="patients_full_na_4556a3_idx"
                    ),
                    models.Index(fields=["phone"], name="patients_phone_ef6690_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("test_code", models.CharField(max_length=30, unique=True)),
                ("test_name", models.CharField(max_length=180)),
                ("short_name", models.CharField(blank=True, max_length=80)),
                (
                    "rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("unit", models.CharField(blank=True, max_length=50)),
                (
                    "result_type",
                    models.CharField(
                        choices=[
                            ("numeric", "Numeric"),
                            ("text", "Text"),
                            ("choice", "Choice"),
                            ("panel", "Panel"),
                        ],
                        default="numeric",
                        max_length=20,
                    ),
                ),
                ("is_group", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tests",
                        to="lab.department",
                    ),
                ),
            ],
            options={
                "db_table": "tests",
                "ordering": ["department__report_order", "test_name"],
            },
        ),
        migrations.CreateModel(
            name="TestGroupItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_order", models.PositiveIntegerField(default=0)),
                (
                    "child_test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_groups",
                        to="lab.test",
                    ),
                ),
                (
                    "parent_test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_items",
                        to="lab.test",
                    ),
                ),
            ],
            options={
                "db_table": "test_group_items",
                "ordering": ["line_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="TestReferenceRange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("any", "Any"),
                            ("male", "Male"),
                            ("female", "Female"),
                        ],
                        default="any",
                        max_length=10,
                    ),
                ),
                ("age_years_min", models.PositiveIntegerField(blank=True, null=True)),
                ("age_years_max", models.PositiveIntegerField(blank=True, null=True)),
                ("age_months_min", models.PositiveIntegerField(blank=True, null=True)),
                ("age_months_max", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "operator",
                    models.CharField(
                        choices=[
                            ("between", "Between"),
                            ("lt", "Less Than"),
                            ("lte", "Less Than or Equal"),
                            ("gt", "Greater Than"),
                            ("gte", "Greater Than or Equal"),
                            ("text", "Text Only"),
                        ],
                        default="between",
                        max_length=20,
                    ),
                ),
                (
                    "min_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "max_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("display_text", models.CharField(blank=True, max_length=255)),
                ("unit", models.CharField(blank=True, max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reference_ranges",
                        to="lab.test",
                    ),
                ),
            ],
            options={
                "db_table": "test_reference_ranges",
                "ordering": ["test", "gender", "age_years_min", "age_months_min", "id"],
            },
        ),
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("lab_no", models.CharField(max_length=30, unique=True)),
                ("visit_date", models.DateField()),
                ("sample_on", models.DateTimeField()),
                ("ip_no", models.CharField(blank=True, max_length=40)),
                ("out_doctor_name", models.CharField(blank=True, max_length=150)),
                ("corporate_name", models.CharField(blank=True, max_length=150)),
                (
                    "pay_mode",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("card", "Card"),
                            ("upi", "UPI"),
                            ("credit", "Credit"),
                        ],
                        default="cash",
                        max_length=20,
                    ),
                ),
                (
                    "discount_mode",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("corporate", "Corporate"),
                            ("staff", "Staff"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                (
                    "discount_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("discount_reason", models.CharField(blank=True, max_length=255)),
                ("note", models.TextField(blank=True)),
                (
                    "round_off",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "gross_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "net_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "received_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "balance_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("registered", "Registered"),
                            ("result_entered", "Result Entered"),
                            ("authorized", "Authorized"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="registered",
                        max_length=20,
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="visits",
                        to="lab.doctor",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="visits",
                        to="lab.hospital",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="visits",
                        to="lab.patient",
                    ),
                ),
            ],
            options={
                "db_table": "visits",
                "ordering": ["-visit_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="VisitTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test_name_snapshot", models.CharField(max_length=180)),
                (
                    "rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "discount_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("line_order", models.PositiveIntegerField(default=0)),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="visit_tests",
                        to="lab.test",
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visit_tests",
                        to="lab.visit",
                    ),
                ),
            ],
            options={
                "db_table": "visit_tests",
                "ordering": ["line_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="TestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("result_value", models.CharField(blank=True, max_length=120)),
                (
                    "result_value_numeric",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=12, null=True
                    ),
                ),
                ("result_text", models.TextField(blank=True)),
                ("unit", models.CharField(blank=True, max_length=50)),
                ("reference_range_text", models.CharField(blank=True, max_length=255)),
                ("remarks", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("entered", "Entered"),
                            ("authorized", "Authorized"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("entered_at", models.DateTimeField(blank=True, null=True)),
                ("authorized_at", models.DateTimeField(blank=True, null=True)),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="results",
                        to="lab.test",
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="lab.visit",
                    ),
                ),
                (
                    "visit_test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="lab.visittest",
                    ),
                ),
            ],
            options={
                "db_table": "test_results",
                "ordering": ["visit", "visit_test__line_order", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="test",
            index=models.Index(fields=["test_name"], name="tests_test_na_caa548_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="testgroupitem",
            unique_together={("parent_test", "child_test")},
        ),
        migrations.AddIndex(
            model_name="visit",
            index=models.Index(fields=["lab_no"], name="visits_lab_no_b4a2f4_idx"),
        ),
        migrations.AddIndex(
            model_name="visit",
            index=models.Index(fields=["visit_date"], name="visits_visit_d_74ae9d_idx"),
        ),
        migrations.AddIndex(
            model_name="testresult",
            index=models.Index(fields=["status"], name="test_result_status_854a77_idx"),
        ),
    ]
