# Generated by Django 6.0.3 on 2026-05-20 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "units",
                "ordering": ["name"],
            },
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE tests "
                        "ADD COLUMN IF NOT EXISTS default_amount numeric(10,2) NOT NULL DEFAULT 0;"
                    ),
                    reverse_sql="ALTER TABLE tests DROP COLUMN IF EXISTS default_amount;",
                ),
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE tests "
                        "ADD COLUMN IF NOT EXISTS default_discount_percent numeric(5,2) NOT NULL DEFAULT 0;"
                    ),
                    reverse_sql="ALTER TABLE tests DROP COLUMN IF EXISTS default_discount_percent;",
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="test",
                    name="default_amount",
                    field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                migrations.AddField(
                    model_name="test",
                    name="default_discount_percent",
                    field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
            ],
        ),
    ]
