# Generated by Django 6.0.3 on 2026-06-05 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0002_unit_test_default_amount_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="testreferencerange",
            options={"ordering": ["test", "gender", "id"]},
        ),
        migrations.RemoveField(
            model_name="testreferencerange",
            name="age_months_max",
        ),
        migrations.RemoveField(
            model_name="testreferencerange",
            name="age_months_min",
        ),
        migrations.RemoveField(
            model_name="testreferencerange",
            name="age_years_max",
        ),
        migrations.RemoveField(
            model_name="testreferencerange",
            name="age_years_min",
        ),
    ]
