# Generated by Django 5.2.15 on 2026-06-18 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0003_alter_testreferencerange_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReagentItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150, unique=True)),
                (
                    "item_code",
                    models.CharField(blank=True, max_length=30, null=True, unique=True),
                ),
                (
                    "unit_of_measure",
                    models.CharField(
                        help_text="e.g. ml, Box, Packet, Vial", max_length=50
                    ),
                ),
                (
                    "min_stock_level",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "quantity_in_stock",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
            ],
            options={
                "db_table": "reagent_items",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StockTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tx_type",
                    models.CharField(
                        choices=[
                            ("inward", "Inward (Receipt)"),
                            ("outward", "Outward (Consumption)"),
                        ],
                        max_length=10,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=12)),
                ("batch_no", models.CharField(blank=True, max_length=50)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("received_date", models.DateField()),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("supplier_name", models.CharField(blank=True, max_length=150)),
                ("invoice_no", models.CharField(blank=True, max_length=50)),
                ("narration", models.TextField(blank=True)),
                (
                    "reagent_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="lab.reagentitem",
                    ),
                ),
            ],
            options={
                "db_table": "stock_transactions",
                "ordering": ["-received_date", "-id"],
            },
        ),
    ]
