# Generated by Django 6.0.3 on 2026-06-18 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0004_reagentitem_stocktransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="reagentitem",
            name="bottle_size",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Bottle size in ml, e.g. 500",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="reagentitem",
            name="quantity_in_use",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="reagentitem",
            name="reagent_type",
            field=models.CharField(
                choices=[
                    ("liquid", "Liquid Reagent"),
                    ("card", "Card / Rapid Test"),
                    ("other", "Other General Item"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="stocktransaction",
            name="bottle_size",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="stocktransaction",
            name="test_result",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_transactions",
                to="lab.testresult",
            ),
        ),
        migrations.AddField(
            model_name="test",
            name="reagent_auto_reduce",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="test",
            name="reagent_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tests",
                to="lab.reagentitem",
            ),
        ),
        migrations.AddField(
            model_name="test",
            name="reagent_quantity",
            field=models.DecimalField(decimal_places=4, default=1, max_digits=12),
        ),
        migrations.AlterField(
            model_name="stocktransaction",
            name="tx_type",
            field=models.CharField(
                choices=[
                    ("inward", "Inward (Receipt)"),
                    ("outward", "Outward (Consumption)"),
                    ("open_bottle", "Open Bottle"),
                    ("discard_in_use", "Discard Empty Bottle"),
                ],
                max_length=15,
            ),
        ),
    ]
