# Generated by Django 5.2.15 on 2026-06-18 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_labuser_loginsession_last_activity_and_more'),
        ('lab', '0005_reagentitem_bottle_size_reagentitem_quantity_in_use_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='cancel_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_visits', to='accounts.labuser'),
        ),
    ]
