# Generated by Django 5.2.15 on 2026-06-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0006_visit_cancel_reason_visit_cancelled_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscountReason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reason_text", models.CharField(max_length=255, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "discount_reasons",
                "ordering": ["reason_text"],
            },
        ),
        migrations.CreateModel(
            name="LabCustomization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("section", models.CharField(max_length=50)),
                ("key", models.CharField(max_length=50, unique=True)),
                ("value", models.TextField(blank=True)),
            ],
            options={
                "db_table": "lab_customizations",
                "ordering": ["section", "key"],
            },
        ),
        migrations.CreateModel(
            name="Method",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "methods",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SMSTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_name",
                    models.CharField(
                        choices=[
                            ("registration", "On Patient Registration"),
                            ("result_ready", "On Result Ready"),
                            ("balance_due", "On Balance Due"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("template_text", models.TextField()),
            ],
            options={
                "db_table": "sms_templates",
                "ordering": ["event_name"],
            },
        ),
        migrations.CreateModel(
            name="Technology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "technologies",
                "ordering": ["name"],
            },
        ),
    ]
