# Generated by Django 5.2.15 on 2026-06-19 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0007_discountreason_labcustomization_method_smstemplate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="technology",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tests",
                to="lab.technology",
            ),
        ),
    ]
