# Generated by Django 5.2.15 on 2026-06-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0008_test_technology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='reagent_quantity',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
    ]
