# Generated by Django

from django.db import migrations


def reproduce_units(apps, schema_editor):
    Unit = apps.get_model('lab', 'Unit')
    Test = apps.get_model('lab', 'Test')

    # Clear existing units
    Unit.objects.all().delete()

    # Scan for unique test units
    test_units = Test.objects.exclude(unit="").exclude(unit__isnull=True).values_list("unit", flat=True).distinct()
    
    unique_unit_names = sorted(list(set(name.strip() for name in test_units if name.strip())))
    
    # Recreate
    for name in unique_unit_names:
        Unit.objects.create(name=name, is_active=True)


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0009_alter_test_reagent_quantity'),
    ]

    operations = [
        migrations.RunPython(reproduce_units),
    ]
