# Generated by Django 5.2.15 on 2026-06-23 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0010_reproduce_units'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testreferencerange',
            options={'ordering': ['component', 'reference_group', 'id']},
        ),
        migrations.RemoveField(
            model_name='testreferencerange',
            name='gender',
        ),
        migrations.AddField(
            model_name='testreferencerange',
            name='reference_group',
            field=models.CharField(choices=[('COMMON', 'Common'), ('MALE', 'Male'), ('FEMALE', 'Female'), ('CHILD', 'Child')], default='COMMON', max_length=20),
        ),
        migrations.AlterField(
            model_name='testreferencerange',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reference_ranges', to='lab.test'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='results', to='lab.test'),
        ),
        migrations.CreateModel(
            name='TestComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component_name', models.CharField(max_length=255)),
                ('result_type', models.CharField(choices=[('numeric', 'Numeric'), ('text', 'Text'), ('choice', 'Choice'), ('panel', 'Panel')], default='numeric', max_length=20)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('display_order', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='lab.test')),
            ],
            options={
                'db_table': 'test_components',
                'ordering': ['test', 'display_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='testreferencerange',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reference_ranges', to='lab.testcomponent'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='results', to='lab.testcomponent'),
        ),
    ]
