# Generated by Django 5.2.15 on 2026-06-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0011_alter_testreferencerange_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='formula',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
